version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "sendo-kakeru"
    assignees:
      - "sendo-kakeru"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: 'react-router-flash-message'

  - package-ecosystem: npm
    directories:
      - /
      - /example
    schedule:
      interval: "weekly"
    reviewers:
      - "sendo-kakeru"
    assignees:
      - "sendo-kakeru"
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      react-router:
        patterns:
          - react-router
          - "@types/react-router"
          - "@react-router/*"
