name: '🐛 Bug report'
description: |
  Please report the bug.
  If you're not sure if it's a bug or not, please use the template `Support Request` instead.
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false