blank_issues_enabled: false
contact_links:
  - name: Issue of Standard Registry
    url: https://github.com/sendo-kakeru/react-router-flash-message/issues
    about: Please report issues about aqua Standard Registry