name: Support Request
description: |
  Please use this template when you face any problem (not bug) and need our help.
  If you're not sure if it's a bug or not, please use this template.
labels:
  - support-request
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      value: |
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false